---
engines:
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
  reek:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  # https://github.com/rubysec/bundler-audit/pull/87/commits/59b50f8423cba24dbb6cde3ad7df0358c77bbd29
  # bundler-audit:
  #   enabled: true
ratings:
  paths:
  # - Gemfile.lock
  - "**.rb"
exclude_paths:
- "test/"
- "spec/"
- "**/vendor/"
