# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

require: rubocop-rspec

# Use this to ingore current violations (and fix them later) run:
# bundle exec rubocop --auto-gen-config
inherit_from: .rubocop_todo.yml

AllCops:
  EnabledByDefault: true

# Redefined

Metrics/LineLength:
  Max: 120

# Disabled

Style/Documentation:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false
