# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

require: rubocop-rspec

# Use this to ingore current violations (and fix them later) run:
# bundle exec rubocop --auto-gen-config
inherit_from: .rubocop_todo.yml

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.4

# Redefined

Metrics/LineLength:
  Max: 120

# Disabled

Style/Documentation:
  Enabled: false

# Disabled (again)

Style/Copyright:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false
