sudo: false
language: ruby
rvm:
  - 2.4.0
before_install:
  - gem update --system --no-doc
  - gem install bundler -v 1.14.6 --no-doc
after_success:
  - bundle exec codeclimate-test-reporter
# `cache` is only available for private projects
cache: bundler
